apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyproxy
  labels:
    io.kompose.service: tinyproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tinyproxy
  template:
    metadata:
      labels:
        io.kompose.service: tinyproxy
    spec:
      containers:
      - image: kalaksi/tinyproxy
        name: tinyproxy
        ports:
          - containerPort: 8888
        resources: {}
        securityContext:
          capabilities:
            drop:
            - ALL
        env:
          - { name: ALLOWED_NETWORKS, value: 10.0.0.0/8 }
          - { name: DISABLE_VIA_HEADER, value: "yes" }
          - { name: MAX_CLIENTS, value: "100" }
          - { name: MAX_SPARE_SERVERS, value: "100" }
          - { name: MIN_SPARE_SERVERS, value: "50" }
          - { name: STAT_HOST, value: tinyproxy.stats }
          - { name: LOG_LEVEL, value: Notice }
          - { name: TIMEOUT, value: "900" }
          - { name: AUTH_USER, value: "" }
          - { name: AUTH_PASSWORD, value: "" }
